//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnWpf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LetterRecord
    {
        public long Id { get; set; }
        public long LetterNumber { get; set; }
        public string ReciptDate { get; set; }
        public long TopicAreaID { get; set; }
        public long PoliceStationID { get; set; }
        public long PoliceOfficerID { get; set; }
        public long DRNumber { get; set; }
        public string DRDate { get; set; }
        public Nullable<long> StatusID { get; set; }
        public string Remarks { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual PoliceOfficer PoliceOfficer { get; set; }
        public virtual PoliceStation PoliceStation { get; set; }
        public virtual TopicsAndArea TopicsAndArea { get; set; }
    }
}
